### ISSUE TITLE
Feature: click to copy on clipboard

### ISSUE THREAD

**Issue by pandurijal** [timmybytes/color-chooser#1]
Hello. This seems a good web app, and would be more epic if the user can just use a single click to copy color code on the clipboard. Can I work on this issue? Thank you in advance.

**Comment by timmybytes** [comment]
Hey there! Thanks for the interest. This is a feature I’ve been wanting to implement anyway, so feel free to fork and work on a feature branch. I haven’t had time to refactor the code as much as I’d like yet, so I apologize if things are a little bit of a mess!

**Comment by pandurijal** [comment]
Aight noted, will do. Thanks!
